version: '2'
services:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/dockerhub_mirror/nginx
    restart: always
    container_name: nginx_container
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d/:/etc/nginx/conf.d/
      - ./nginx/html/:/var/www/html/
      - ./nginx/logs/:/var/log/nginx/
    environment:
      LANG: en_US.UTF-8
    ports:
      - 8088:80
    networks:
      - jeecg-boot
  jeecg-boot-mysql:
    image: registry.cn-hangzhou.aliyuncs.com/jeecgdocker/mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: gopha1996
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_HOST: '%'
    restart: always
    container_name: jeecg-boot-mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --default-authentication-plugin=caching_sha2_password
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3399:3306
    networks:
      - jeecg-boot
  jeecg-boot-redis:
    image: registry.cn-hangzhou.aliyuncs.com/jeecgdocker/redis:5.0
    ports:
      - 6399:6379
    restart: always
    hostname: jeecg-boot-redis
    container_name: jeecg-boot-redis
    networks:
      - jeecg-boot

  jeecg-boot-system:
    build:
      context: ./jeecg-boot-system
    restart: on-failure
    depends_on:
      - jeecg-boot-mysql
      - jeecg-boot-redis
    container_name: jeecg-boot-system
    image: jeecg-boot-system
    hostname: jeecg-boot-system
    volumes:
      - ./jeecg-system-start/upload:/opt/upFiles
      - ./jeecg-system-start/webapp:/opt/webapp
    ports:
      - 8086:8080
    networks:
      - jeecg-boot
networks:
  jeecg-boot:
    name: jeecg_boot
